In [1]:
import numpy as np
import pandas as pd 

### Looking at the words data

In [2]:
#loading
words_df = pd.read_csv('words.csv')
words_df.head()

Unnamed: 0          0        1         2    3    4    5    6    7    8  \
0           0  communism      NaN       NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1           1       dark     neon       NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2           2       dont     talk        to   me  NaN  NaN  NaN  NaN  NaN   
3           3       good    night  princess  NaN  NaN  NaN  NaN  NaN  NaN   
4           4       good  morning  princess  NaN  NaN  NaN  NaN  NaN  NaN   

     9   10  
0  NaN  NaN  
1  NaN  NaN  
2  NaN  NaN  
3  NaN  NaN  
4  NaN  NaN

In [3]:
words_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10183 entries, 0 to 10182
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  10183 non-null  int64 
 1   0           10165 non-null  object
 2   1           6689 non-null   object
 3   2           2181 non-null   object
 4   3           676 non-null    object
 5   4           218 non-null    object
 6   5           80 non-null     object
 7   6           31 non-null     object
 8   7           13 non-null     object
 9   8           7 non-null      object
 10  9           3 non-null      object
 11  10          2 non-null      object
dtypes: int64(1), object(11)
memory usage: 954.8+ KB


In [4]:
# deleting the unnamed 0 column since it's a duplicate of the index
words_df.drop('Unnamed: 0', inplace=True, axis=1)
words_df.head()

0        1         2    3    4    5    6    7    8    9   10
0  communism      NaN       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1       dark     neon       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2       dont     talk        to   me  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3       good    night  princess  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4       good  morning  princess  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [5]:
#looking at nul values
words_df.isnull().sum()

0        18
1      3494
2      8002
3      9507
4      9965
5     10103
6     10152
7     10170
8     10176
9     10180
10    10181
dtype: int64

Since the columns represents words of a sentance, it is normal no have null values in column 1 to 10, however the null values at column 0 must be handeled, i'll probably delete the rows but i'll do the handling after i merge the words dataframe with the colors dataframe 

In [6]:
#renaming columns
words_df.rename(columns = {'0':'word1', '1':'word2', '2':'word3', '3':'word4', '4':'word5', '5':'word6', '6':'word7', '7':'word8', '8':'word9', '9':'word10', '10':'word11'}, inplace = True)
words_df.head()

word1    word2     word3 word4 word5 word6 word7 word8 word9 word10  \
0  communism      NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
1       dark     neon       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
2       dont     talk        to    me   NaN   NaN   NaN   NaN   NaN    NaN   
3       good    night  princess   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
4       good  morning  princess   NaN   NaN   NaN   NaN   NaN   NaN    NaN   

  word11  
0    NaN  
1    NaN  
2    NaN  
3    NaN  
4    NaN

In [7]:
#checking duplicates
words_df.duplicated().sum()

1653

In [8]:
#looking at the duplicates
words_df[words_df.duplicated()]

word1         word2 word3 word4 word5 word6 word7 word8 word9  \
77          fresh  sophisticate   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
220          blue           NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
290         pinks           NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
313          cute           NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
334        wizard           NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
...           ...           ...   ...   ...   ...   ...   ...   ...   ...   
10172  watermelon           NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
10177      shades            of   red   NaN   NaN   NaN   NaN   NaN   NaN   
10178       grace           NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
10179      pastel          mint   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
10180      forget           NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

      word10 word11  
77       NaN    NaN  
220      NaN    NaN  
290      NaN    NaN  
313      NaN    NaN  
334      NaN    NaN  
...      ...    ...  
10172    NaN    NaN  
10177    NaN    NaN  
10178    NaN    NaN  
10179    NaN    NaN  
10180    NaN    NaN  

[1653 rows x 11 columns]

I'm not sure about these duplicated rows, do they have the exact same palette in the colors daraframe? i'll save the their indix in a list and check pn them after merging.

In [9]:
dup_words = words_df[words_df.duplicated()].index.tolist()
dup_words[0:5]

[77, 220, 290, 313, 334]

### Looking at the colors data

In [10]:
#loading
colors_df = pd.read_csv('colors.csv')
colors_df.head()

Unnamed: 0                0                1                2  \
0           0    (206, 18, 18)    (193, 27, 27)  (201, 149, 149)   
1           1    (116, 35, 35)   (117, 122, 37)    (35, 118, 41)   
2           2  (192, 237, 251)  (192, 221, 235)  (192, 205, 219)   
3           3     (49, 40, 66)     (65, 55, 84)    (87, 73, 105)   
4           4  (246, 245, 230)  (244, 236, 217)  (244, 226, 204)   

                 3                4  
0  (191, 138, 138)    (165, 27, 27)  
1    (44, 41, 114)   (115, 36, 116)  
2  (192, 189, 203)  (192, 173, 187)  
3  (120, 100, 131)  (156, 137, 161)  
4  (240, 208, 186)  (234, 189, 169)

In [11]:
colors_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10183 entries, 0 to 10182
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  10183 non-null  int64 
 1   0           10183 non-null  object
 2   1           10183 non-null  object
 3   2           10183 non-null  object
 4   3           10183 non-null  object
 5   4           10183 non-null  object
dtypes: int64(1), object(5)
memory usage: 477.5+ KB


In [12]:
# deleting the unnamed 0 column since it's a duplicate of the index
colors_df.drop('Unnamed: 0', inplace=True, axis=1)
colors_df.head()

0                1                2                3  \
0    (206, 18, 18)    (193, 27, 27)  (201, 149, 149)  (191, 138, 138)   
1    (116, 35, 35)   (117, 122, 37)    (35, 118, 41)    (44, 41, 114)   
2  (192, 237, 251)  (192, 221, 235)  (192, 205, 219)  (192, 189, 203)   
3     (49, 40, 66)     (65, 55, 84)    (87, 73, 105)  (120, 100, 131)   
4  (246, 245, 230)  (244, 236, 217)  (244, 226, 204)  (240, 208, 186)   

                 4  
0    (165, 27, 27)  
1   (115, 36, 116)  
2  (192, 173, 187)  
3  (156, 137, 161)  
4  (234, 189, 169)

In [13]:
#Renaming the columns
colors_df.rename(columns = {'0':'Color1', '1':'Color2', '2':'Color3', '3':'Color4', '4':'Color5'}, inplace = True)
colors_df.head()

Color1           Color2           Color3           Color4  \
0    (206, 18, 18)    (193, 27, 27)  (201, 149, 149)  (191, 138, 138)   
1    (116, 35, 35)   (117, 122, 37)    (35, 118, 41)    (44, 41, 114)   
2  (192, 237, 251)  (192, 221, 235)  (192, 205, 219)  (192, 189, 203)   
3     (49, 40, 66)     (65, 55, 84)    (87, 73, 105)  (120, 100, 131)   
4  (246, 245, 230)  (244, 236, 217)  (244, 226, 204)  (240, 208, 186)   

            Color5  
0    (165, 27, 27)  
1   (115, 36, 116)  
2  (192, 173, 187)  
3  (156, 137, 161)  
4  (234, 189, 169)

In [14]:
#checking duplicates
colors_df.duplicated().sum()

15

In [15]:
colors_df[colors_df.duplicated()]

Color1           Color2           Color3           Color4  \
966   (238, 238, 238)  (221, 221, 221)  (204, 204, 204)  (187, 187, 187)   
1797        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)   
1930  (238, 238, 238)  (221, 221, 221)  (204, 204, 204)  (187, 187, 187)   
2627        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)   
4414        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)   
6257  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   
7047        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)   
7229  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   
7357  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   
7844  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   
7867        (0, 0, 0)  (255, 255, 255)        (0, 0, 0)  (255, 255, 255)   
9339  (238, 238, 238)  (221, 221, 221)  (204, 204, 204)  (187, 187, 187)   
9347        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)   
9351  (238, 238, 238)  (221, 221, 221)  (204, 204, 204)  (187, 187, 187)   
9954      (255, 0, 0)    (255, 255, 0)      (0, 255, 0)    (0, 255, 255)   

               Color5  
966   (170, 170, 170)  
1797        (0, 0, 0)  
1930  (170, 170, 170)  
2627        (0, 0, 0)  
4414        (0, 0, 0)  
6257  (255, 255, 255)  
7047        (0, 0, 0)  
7229  (255, 255, 255)  
7357  (255, 255, 255)  
7844  (255, 255, 255)  
7867        (0, 0, 0)  
9339  (170, 170, 170)  
9347        (0, 0, 0)  
9351  (170, 170, 170)  
9954      (0, 0, 255)

Some of the duplicated palettes are fully black, fully white, a mix of both, or a normal palette. This could be related to the words they are assigned to, for example: white, light can be both assigned to fully white palett. I won't make a desion on these duplicates till I merge the words with the colors. However I'll save the index of these duplicate for now and check on them later after merging.

In [16]:
#Saving index on a list
dup_colors = colors_df[colors_df.duplicated()].index.tolist()
dup_colors[0:5]

[966, 1797, 1930, 2627, 4414]

In [17]:
#Trying to display each color using style
colors_df.sample(10).style.applymap(lambda x:"background-color: rgb%s"%x)


### Merging the two dataframes

In [18]:
text2palette_df = words_df.join(colors_df)
text2palette_df.head()

word1    word2     word3 word4 word5 word6 word7 word8 word9 word10  \
0  communism      NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
1       dark     neon       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
2       dont     talk        to    me   NaN   NaN   NaN   NaN   NaN    NaN   
3       good    night  princess   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
4       good  morning  princess   NaN   NaN   NaN   NaN   NaN   NaN    NaN   

  word11           Color1           Color2           Color3           Color4  \
0    NaN    (206, 18, 18)    (193, 27, 27)  (201, 149, 149)  (191, 138, 138)   
1    NaN    (116, 35, 35)   (117, 122, 37)    (35, 118, 41)    (44, 41, 114)   
2    NaN  (192, 237, 251)  (192, 221, 235)  (192, 205, 219)  (192, 189, 203)   
3    NaN     (49, 40, 66)     (65, 55, 84)    (87, 73, 105)  (120, 100, 131)   
4    NaN  (246, 245, 230)  (244, 236, 217)  (244, 226, 204)  (240, 208, 186)   

            Color5  
0    (165, 27, 27)  
1   (115, 36, 116)  
2  (192, 173, 187)  
3  (156, 137, 161)  
4  (234, 189, 169)

In [19]:
text2palette_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10183 entries, 0 to 10182
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   word1   10165 non-null  object
 1   word2   6689 non-null   object
 2   word3   2181 non-null   object
 3   word4   676 non-null    object
 4   word5   218 non-null    object
 5   word6   80 non-null     object
 6   word7   31 non-null     object
 7   word8   13 non-null     object
 8   word9   7 non-null      object
 9   word10  3 non-null      object
 10  word11  2 non-null      object
 11  Color1  10183 non-null  object
 12  Color2  10183 non-null  object
 13  Color3  10183 non-null  object
 14  Color4  10183 non-null  object
 15  Color5  10183 non-null  object
dtypes: object(16)
memory usage: 1.2+ MB


In [20]:
#checking nulls
text2palette_df.isnull().sum()

word1        18
word2      3494
word3      8002
word4      9507
word5      9965
word6     10103
word7     10152
word8     10170
word9     10176
word10    10180
word11    10181
Color1        0
Color2        0
Color3        0
Color4        0
Color5        0
dtype: int64

In [21]:
#checking the rows that has null values in word1
text2palette_df[text2palette_df['word1'].isnull()]

word1    word2   word3   word4 word5 word6 word7 word8 word9 word10  \
214     NaN    hours   crazy     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
542     NaN   shades      of    grey   NaN   NaN   NaN   NaN   NaN    NaN   
1859    NaN   shades      of   green   NaN   NaN   NaN   NaN   NaN    NaN   
5409    NaN   shades      of    gray   NaN   NaN   NaN   NaN   NaN    NaN   
5670    NaN   shades      of   brown   NaN   NaN   NaN   NaN   NaN    NaN   
6231    NaN   shades      of    grey   NaN   NaN   NaN   NaN   NaN    NaN   
6257    NaN      NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
6737    NaN   shades      of  orange   NaN   NaN   NaN   NaN   NaN    NaN   
6738    NaN   shades      of     red   NaN   NaN   NaN   NaN   NaN    NaN   
6739    NaN   shades      of    pink   NaN   NaN   NaN   NaN   NaN    NaN   
7229    NaN      NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
8821    NaN   shades      of    grey   NaN   NaN   NaN   NaN   NaN    NaN   
9401    NaN  percent  chance      of  rain   NaN   NaN   NaN   NaN    NaN   
9823    NaN    greys     and     NaN  reds   NaN   NaN   NaN   NaN    NaN   
9834    NaN    greys     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
9835    NaN   shades      of    blue   NaN   NaN   NaN   NaN   NaN    NaN   
9965    NaN    green     NaN  purple   NaN  blue   NaN   NaN   NaN    NaN   
10105   NaN   shades      of   blush   NaN   NaN   NaN   NaN   NaN    NaN   

      word11           Color1           Color2           Color3  \
214      NaN    (102, 255, 0)    (0, 255, 252)    (255, 0, 244)   
542      NaN  (216, 216, 216)  (167, 167, 167)  (103, 103, 103)   
1859     NaN     (0, 156, 26)     (34, 182, 0)     (38, 204, 0)   
5409     NaN  (236, 236, 236)  (221, 221, 221)  (204, 204, 204)   
5670     NaN  (236, 208, 124)   (178, 152, 92)   (141, 116, 78)   
6231     NaN  (221, 219, 219)  (221, 221, 221)  (144, 142, 142)   
6257     NaN  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   
6737     NaN   (240, 161, 80)   (240, 149, 55)   (244, 128, 32)   
6738     NaN     (249, 70, 9)      (251, 1, 1)    (227, 41, 20)   
6739     NaN  (249, 187, 230)  (242, 158, 200)  (238, 115, 196)   
7229     NaN  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   
8821     NaN     (21, 21, 21)     (54, 54, 54)     (90, 90, 90)   
9401     NaN  (133, 226, 255)  (139, 255, 219)   (44, 174, 133)   
9823     NaN  (116, 111, 111)  (163, 161, 161)  (204, 204, 204)   
9834     NaN  (225, 221, 221)  (195, 190, 190)  (180, 173, 173)   
9835     NaN  (171, 188, 234)  (146, 180, 227)  (123, 164, 221)   
9965     NaN    (45, 199, 45)    (74, 46, 206)   (54, 219, 147)   
10105    NaN  (243, 227, 232)  (239, 217, 223)  (252, 217, 227)   

                Color4           Color5  
214        (255, 0, 0)    (255, 231, 0)  
542       (49, 49, 49)        (0, 0, 0)  
1859   (123, 227, 130)  (210, 242, 212)  
5409   (187, 187, 187)  (170, 170, 170)  
5670     (116, 94, 52)     (96, 80, 40)  
6231   (187, 187, 187)  (139, 136, 136)  
6257   (255, 255, 255)  (255, 255, 255)  
6737    (240, 117, 15)    (199, 103, 6)  
6738     (199, 56, 19)    (165, 21, 13)  
6739    (244, 83, 173)   (242, 11, 151)  
7229   (255, 255, 255)  (255, 255, 255)  
8821   (118, 118, 118)  (156, 154, 154)  
9401    (48, 149, 180)   (148, 69, 193)  
9823     (244, 19, 19)    (255, 91, 91)  
9834   (210, 210, 210)  (235, 236, 234)  
9835    (98, 141, 214)   (76, 116, 201)  
9965   (140, 116, 255)   (34, 205, 253)  
10105  (252, 206, 219)  (255, 202, 217)

There are sentacies that start from word2 instead of word1, this should be handled and shifted to word1 (??). For now let's start by deleting the fully null rows, row number 6257 and 7229. But before deleting the row and changing the indexing, let's check on the duplicated rows that we have saved before form the colors dataframe, we assumed that it's related to words that represent black or white.

In [22]:
text2palette_df.iloc[dup_colors,:]

word1     word2     word3 word4 word5 word6 word7 word8 word9 word10  \
966        not     found       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
1797      coal       NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
1930     light     greys       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
2627  darkness       NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
4414       all     black       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
6257       NaN       NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7047      dark      shit       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7229       NaN       NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7357      none       NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7844     empty       NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7867     zebra       NaN       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
9339    fallen  colorite       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
9347      lost        in  universe   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
9351      grey      clay       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
9954   rainbow      neon       NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   

     word11           Color1           Color2           Color3  \
966     NaN  (238, 238, 238)  (221, 221, 221)  (204, 204, 204)   
1797    NaN        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)   
1930    NaN  (238, 238, 238)  (221, 221, 221)  (204, 204, 204)   
2627    NaN        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)   
4414    NaN        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)   
6257    NaN  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   
7047    NaN        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)   
7229    NaN  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   
7357    NaN  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   
7844    NaN  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   
7867    NaN        (0, 0, 0)  (255, 255, 255)        (0, 0, 0)   
9339    NaN  (238, 238, 238)  (221, 221, 221)  (204, 204, 204)   
9347    NaN        (0, 0, 0)        (0, 0, 0)        (0, 0, 0)   
9351    NaN  (238, 238, 238)  (221, 221, 221)  (204, 204, 204)   
9954    NaN      (255, 0, 0)    (255, 255, 0)      (0, 255, 0)   

               Color4           Color5  
966   (187, 187, 187)  (170, 170, 170)  
1797        (0, 0, 0)        (0, 0, 0)  
1930  (187, 187, 187)  (170, 170, 170)  
2627        (0, 0, 0)        (0, 0, 0)  
4414        (0, 0, 0)        (0, 0, 0)  
6257  (255, 255, 255)  (255, 255, 255)  
7047        (0, 0, 0)        (0, 0, 0)  
7229  (255, 255, 255)  (255, 255, 255)  
7357  (255, 255, 255)  (255, 255, 255)  
7844  (255, 255, 255)  (255, 255, 255)  
7867  (255, 255, 255)        (0, 0, 0)  
9339  (187, 187, 187)  (170, 170, 170)  
9347        (0, 0, 0)        (0, 0, 0)  
9351  (187, 187, 187)  (170, 170, 170)  
9954    (0, 255, 255)      (0, 0, 255)

yes they are indeed related to words like black and light. we can proceed with deleting the fully NaN rows

In [23]:
#checking the dataframe before deleting the row
text2palette_df.iloc[6255:6260,:]

word1  word2   word3   word4 word5 word6 word7 word8 word9 word10  \
6255   sundance    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
6256       come      a  little  closer   NaN   NaN   NaN   NaN   NaN    NaN   
6257        NaN    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
6258      still  smoke     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
6259  daydreams    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   

     word11           Color1           Color2           Color3  \
6255    NaN    (0, 178, 182)   (29, 195, 182)   (74, 223, 182)   
6256    NaN     (69, 29, 11)     (214, 86, 0)   (255, 93, 126)   
6257    NaN  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   
6258    NaN  (209, 219, 221)  (206, 209, 214)  (197, 197, 197)   
6259    NaN  (167, 227, 192)  (123, 186, 166)   (85, 130, 180)   

               Color4           Color5  
6255  (187, 234, 121)   (255, 248, 93)  
6256  (251, 142, 175)  (231, 179, 255)  
6257  (255, 255, 255)  (255, 255, 255)  
6258  (175, 201, 199)  (186, 184, 175)  
6259  (127, 138, 193)  (169, 154, 234)

In [24]:
text2palette_df.iloc[7225:7230,:]

word1   word2 word3 word4 word5 word6 word7 word8 word9 word10  \
7225      used     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7226     golds  yellow   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7227       ice    like   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7228  vampires     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7229       NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   

     word11           Color1           Color2           Color3  \
7225    NaN   (207, 160, 16)   (232, 179, 12)   (188, 146, 14)   
7226    NaN    (255, 238, 0)   (255, 225, 53)   (255, 227, 45)   
7227    NaN  (234, 225, 225)  (176, 210, 219)  (134, 134, 242)   
7228    NaN     (99, 68, 68)    (154, 49, 12)    (221, 38, 38)   
7229    NaN  (255, 255, 255)  (255, 255, 255)  (255, 255, 255)   

               Color4           Color5  
7225   (195, 151, 18)   (245, 208, 10)  
7226    (255, 223, 0)    (255, 215, 0)  
7227    (77, 63, 163)    (34, 41, 128)  
7228    (176, 79, 79)  (178, 153, 153)  
7229  (255, 255, 255)  (255, 255, 255)

In [25]:
#deleting the row and checking the dataframe
text2palette_df = text2palette_df.drop([6257,7229])
text2palette_df.iloc[6255:6260,:]

word1  word2   word3   word4 word5 word6 word7 word8 word9 word10  \
6255   sundance    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
6256       come      a  little  closer   NaN   NaN   NaN   NaN   NaN    NaN   
6258      still  smoke     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
6259  daydreams    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
6260    natalie    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   

     word11           Color1           Color2           Color3  \
6255    NaN    (0, 178, 182)   (29, 195, 182)   (74, 223, 182)   
6256    NaN     (69, 29, 11)     (214, 86, 0)   (255, 93, 126)   
6258    NaN  (209, 219, 221)  (206, 209, 214)  (197, 197, 197)   
6259    NaN  (167, 227, 192)  (123, 186, 166)   (85, 130, 180)   
6260    NaN  (222, 240, 239)  (174, 236, 236)  (167, 210, 229)   

               Color4           Color5  
6255  (187, 234, 121)   (255, 248, 93)  
6256  (251, 142, 175)  (231, 179, 255)  
6258  (175, 201, 199)  (186, 184, 175)  
6259  (127, 138, 193)  (169, 154, 234)  
6260  (221, 206, 238)  (179, 242, 204)

In [26]:
text2palette_df.iloc[7225:7230,:]

word1    word2 word3 word4 word5 word6 word7 word8 word9 word10  \
7226     golds   yellow   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7227       ice     like   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7228  vampires      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7230  icecream  parlour   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7231   mustard      sea   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   

     word11           Color1           Color2           Color3  \
7226    NaN    (255, 238, 0)   (255, 225, 53)   (255, 227, 45)   
7227    NaN  (234, 225, 225)  (176, 210, 219)  (134, 134, 242)   
7228    NaN     (99, 68, 68)    (154, 49, 12)    (221, 38, 38)   
7230    NaN   (29, 229, 211)   (29, 229, 211)   (246, 241, 99)   
7231    NaN  (105, 231, 159)   (240, 196, 25)  (140, 144, 141)   

               Color4           Color5  
7226    (255, 223, 0)    (255, 215, 0)  
7227    (77, 63, 163)    (34, 41, 128)  
7228    (176, 79, 79)  (178, 153, 153)  
7230  (248, 140, 187)  (248, 140, 187)  
7231   (240, 196, 25)  (105, 231, 159)

In [27]:
# fixing the indices
text2palette_df = text2palette_df.reset_index(drop=True) 
text2palette_df.iloc[6255:6260,:]

word1  word2   word3   word4 word5 word6 word7 word8 word9 word10  \
6255   sundance    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
6256       come      a  little  closer   NaN   NaN   NaN   NaN   NaN    NaN   
6257      still  smoke     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
6258  daydreams    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   
6259    natalie    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN    NaN   

     word11           Color1           Color2           Color3  \
6255    NaN    (0, 178, 182)   (29, 195, 182)   (74, 223, 182)   
6256    NaN     (69, 29, 11)     (214, 86, 0)   (255, 93, 126)   
6257    NaN  (209, 219, 221)  (206, 209, 214)  (197, 197, 197)   
6258    NaN  (167, 227, 192)  (123, 186, 166)   (85, 130, 180)   
6259    NaN  (222, 240, 239)  (174, 236, 236)  (167, 210, 229)   

               Color4           Color5  
6255  (187, 234, 121)   (255, 248, 93)  
6256  (251, 142, 175)  (231, 179, 255)  
6257  (175, 201, 199)  (186, 184, 175)  
6258  (127, 138, 193)  (169, 154, 234)  
6259  (221, 206, 238)  (179, 242, 204)

In [28]:
text2palette_df.iloc[7225:7230,:]

word1    word2 word3 word4 word5 word6 word7 word8 word9 word10  \
7225     golds   yellow   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7226       ice     like   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7227  vampires      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7228  icecream  parlour   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
7229   mustard      sea   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   

     word11           Color1           Color2           Color3  \
7225    NaN    (255, 238, 0)   (255, 225, 53)   (255, 227, 45)   
7226    NaN  (234, 225, 225)  (176, 210, 219)  (134, 134, 242)   
7227    NaN     (99, 68, 68)    (154, 49, 12)    (221, 38, 38)   
7228    NaN   (29, 229, 211)   (29, 229, 211)   (246, 241, 99)   
7229    NaN  (105, 231, 159)   (240, 196, 25)  (140, 144, 141)   

               Color4           Color5  
7225    (255, 223, 0)    (255, 215, 0)  
7226    (77, 63, 163)    (34, 41, 128)  
7227    (176, 79, 79)  (178, 153, 153)  
7228  (248, 140, 187)  (248, 140, 187)  
7229   (240, 196, 25)  (105, 231, 159)

In [29]:
#checking on duplicates, is it the same as the words dataframe?
text2palette_df.duplicated().sum()

1

the number of duplicates reduces, this mean that wat was consider a duplicate before in the words or colors dataframe are now different and uique, however we should check more if there were exact words with different color palettes as this will affect the ML model.

In [30]:
#looking at the duplicates
text2palette_df[text2palette_df.duplicated()]

word1 word2 word3 word4 word5 word6 word7 word8 word9 word10 word11  \
7865  zebra   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN   

         Color1           Color2     Color3           Color4     Color5  
7865  (0, 0, 0)  (255, 255, 255)  (0, 0, 0)  (255, 255, 255)  (0, 0, 0)